version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: d19c11/image-upload-download
    ports:
      - "3000:3000"
    volumes:
      - .:/scr/app
      - uploads:/uploads



volumes:
  uploads:
