version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/scr/app
      - uploads:/uploads

#  test:
#    build: .
#    volumes:
#      - .:/src/app
#    command: npm test
#    environment:
#      NODE_ENV: test


volumes:
  uploads:
